export const FETCH_USER = 'FEYCH_USER';
export const FETCH_SURVEYS = 'FETCH_SURVEYS';
export const ADD_ARTICLES = 'ADD_ARTICLES';
export const SET_MESSAGE = 'SET_MESSAGE';
export const RESET_MESSAGE = 'RESET_MESSAGE';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const UPDATE_PERSONAL_AVATAR = 'UPDATE_PERSONAL_AVATAR';
